### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by djmango** [eastriverlee/LLM.swift#10]
<img width="741" alt="image" src="https://github.com/eastriverlee/LLM.swift/assets/28496988/7fdd1d9b-6bb6-4907-a9bd-85f52619465d">

Just gonna submit a PR for this real quick adding a conditional

**Comment by djmango** [comment]
<img width="776" alt="image" src="https://github.com/eastriverlee/LLM.swift/assets/28496988/d38ed7f4-1c35-4259-805e-36d75d8f9adf">
I think its a race condition

**Comment by djmango** [comment]
Or maybe sending in an empty array + content causes this? going to just stop sending empty arrays lol but something to consider

**Comment by eastriverlee** [comment]
okay i should consider switching main logic to `actor`. thank you for reporting.

**Comment by djmango** [comment]
###Instructions###

        Provide exactly two words for a title for the above chat. YOU WILL BE PENALIZED for any additional words, print exactly two words

For some reason this prompt causes a crash - this is the cause of the Int32 crash i posted above

**Comment by eastriverlee** [comment]
if you give me the model, the seed, and the template you've used, it will be easier for me to check later. can you provide me those details?

**Comment by eastriverlee** [comment]
give me any minimal reproducible case if you can please.

**Comment by djmango** [comment]
Running mistral-7b-instruct-v0.2.Q4_K_M.gguf - not sure about seed, how could that be determined? It replicates every time running that string on .respond (using the .mistral template)
