### ISSUE TITLE
Stopping Model Mid-generation

### ISSUE THREAD

**Issue by Someone-Alive** [eastriverlee/LLM.swift#11]
Is there a way to stop the generation process (`bot.respond`) midway? I was wondering because low parameter models (in my experience) tend to easily get stuck and generate nonsense for a long time and the only way to "stop" the model is by restarting the app.

**Comment by eastriverlee** [comment]
good point. i just implemented the functionality([v1.2.4](https://github.com/eastriverlee/LLM.swift/releases/tag/v1.2.4)).
you can now call `LLM.stop()` function anytime and it will stop inferencing.
