### ISSUE TITLE
Make project depend on a specific version of llama.cpp

### ISSUE THREAD

**Issue by yosefahab** [eastriverlee/LLM.swift#15]
**Is your feature request related to a problem? Please describe.**
When adding the project as a package dependency using SPM, it sometimes randomly fails to build with: `Failed to resolve dependencies Dependencies could not be resolved because package 'llm.swift' is required using a stable-version but 'llm.swift' depends on an unstable-version package 'llama.cpp' and root depends on 'llm.swift' 1.4.2.`

**Describe the solution you'd like**
Proposed solution is to change the dependency rule to a specific llama.cpp stable version instead of main branch.

**Comment by eastriverlee** [comment]
i think removing `Package.resolved` will most likely solve the issue.

anyway the this has already been resolved in #5.  
you have the option to use the `pinned` branch instead of the `main` branch.
