### ISSUE TITLE
Apple Watch - example

### ISSUE THREAD

**Issue by ChristianWeyer** [eastriverlee/LLM.swift#18]
Wonderful project! 😎

Do you have a sample that really runs on the Apple Watch?
This would be interesting to see.

**Comment by eastriverlee** [comment]
i don't have an apple watch, but the example i uploaded should work okay, as long as if it's around or below 1B model. i would try tinyllama 1.1b and danube2 1.8b if i had an apple watch. if someone has it please try and tell us the result.
