### ISSUE TITLE
Failing template tests

### ISSUE THREAD

**Issue by atacan** [eastriverlee/LLM.swift#23]
**Describe the bug**

Some tests are failing

**To Reproduce**

run the tests on Xcode Version 15.4 (15F31d)

**Screenshots**

![ScrShot 2024-06-01 at 18 13 09@2x](https://github.com/eastriverlee/LLM.swift/assets/765873/69aac928-7c0e-48ad-8b83-1b3e481119c5)

**Desktop:**
 - Device: MacBook Pro M2 Pro
 - OS: macOS 14.5

**Comment by eastriverlee** [comment]
thank you for finding this! i fixed it. i just forgot to update the tests after changing llama's template a while ago.
