### ISSUE TITLE
Trying to get LLM.swift running on XCode 13.2.1 for iOS

### ISSUE THREAD

**Issue by svdoever** [eastriverlee/LLM.swift#24]
I try to get LLM.swift running on XCode 13.2.1 because my laptop can't upgrade further than Big Sur.

Because LMM.Swift is built with **swift-tools-version: 5.9** it is not possible to use it as a package.

I did check out the repository, but did not understand how to build it.

So I included the LMM.swift file in my code base, after fixing compile errors (see included LLM.swift file), I still get the error:

<img width="403" alt="image" src="https://github.com/eastriverlee/LLM.swift/assets/246842/ac778d8b-d1af-4920-bfd5-22f5f62e39ab">

I added the repository https://github.com/ggerganov/llama.cpp/ as a package, and in the repo I see there is the file **Packages.swift**, and this file uses the **swift-tools-version: 5.5**, which is supported by XCode 13.2.1.

<img width="402" alt="image" src="https://github.com/eastriverlee/LLM.swift/assets/246842/cce4b2a2-9d83-4ed5-9bb6-66b2c8cd35d8">

But in my project I see this:

<img width="520" alt="image" src="https://github.com/eastriverlee/LLM.swift/assets/246842/9eac1f28-36f5-4570-8938-906650d25060">

I'm not an Apple developer, and try to get this working. any ideas are much appreciated.

[LLM.swift.zip](https://github.com/user-attachments/files/15854869/LLM.swift.zip)

**Comment by garfbargle** [comment]
@svdoever Asking to downgrade the swift is going to be rough. but FYI, you can use OpenCore to upgrade to the latest OSes on unsupported macs. I highly recommend it and run it on some pretty old macs and it's solid. https://github.com/dortania/OpenCore-Legacy-Patcher/

**Comment by svdoever** [comment]
Thanks, worked like a breeze! My old Macbook runs latest OSX again, and it is even fast!!
