### ISSUE TITLE
Cannot build in Xcode 16.0 Beta 3

### ISSUE THREAD

**Issue by garfbargle** [eastriverlee/LLM.swift#28]
<img width="850" alt="image" src="https://github.com/user-attachments/assets/c957c428-ee3a-4d73-9ca1-dbf99c9d3e61">

**Comment by garfbargle** [comment]
I created this pull request which fixes the issue, however, I do not fully understand the benefit of the borrowing. https://github.com/eastriverlee/LLM.swift/pull/29

**Comment by eastriverlee** [comment]
thanks for letting me know. borrowing keyword is just explicitly saying it shouldn't be copied, so just use the original pointer. guess swift 6 takes care of this differently. i merged your pull request just now, and i'll look into this more later.
