### ISSUE TITLE
package is broken due to llama.cpp sampling v2 api change

### ISSUE THREAD

**Issue by ferdinandl007** [eastriverlee/LLM.swift#35]
**Describe the bug**

Currently, it is impossible to build this package as you get the following errors.

<img width="1261" alt="Screenshot 2024-09-28 at 19 53 31" src="https://github.com/user-attachments/assets/08ae7f7d-38b1-44ab-b04f-1b52931ac690">

**Comment by Jeky-GC** [comment]
i also facing the same issue
may be llama.cpp update

**Comment by MrFruitDude** [comment]
The pinned branch still works. Make sure to import with @preconcurrency if you're on Swift 6.
