### ISSUE TITLE
App Crashed 

### ISSUE THREAD

**Issue by Rushang007** [eastriverlee/LLM.swift#4]
When I tried to create a demo, add LLM packages, and run the app, the app crashed.

Can you please tell me 
1. how can i get neuralhermes-2.5-mistral-7b.Q5_K_M.gguf file 
2. i want to implement the feature that passes the transcription to the
LLM and receives a summary. 

Thanks in advance

**Comment by eastriverlee** [comment]
app has crashed because you don't have the model.

1. doesn't matter which gguf file you are using.
you can use [huggingface](https://huggingface.co/models?search=gguf) to get the model you want.
2. you can do that by passing appropriate input to LLM. for instance, "summarize this: ...".

**Comment by Rushang007** [comment]
Thanks for quick update @eastriverlee 

I downloaded from [huggingface](https://huggingface.co/models?search=gguf)  but output getting too slow is there any reason?

**Comment by eastriverlee** [comment]
output speed depends on what hardware you are using. if you are testing on mobile, it is an expected behavior. try [tinyllama model](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF) if you're not satisfied with the speed.

**Comment by Rushang007** [comment]
Okey i'll check it 

But i have still question model size in GB So how can we handle while deployment ?

**Comment by eastriverlee** [comment]
there are several ways:
1. get a heavily quantized version.
2. download model dynamically.
3. get a smaller but worse model.

tinyllama is less than a GB when it's quantized, so it should be good already, but there is another smaller model called [litellama](https://huggingface.co/tsunemoto/LiteLlama-460M-1T-GGUF/tree/main).

**Comment by Rushang007** [comment]
OKey 
see my goal is to implement the feature that passes the transcription to the
LLM and receives a summary. 

which is suitable for this goal ? (if possible small size) ?

**Comment by eastriverlee** [comment]
you can either test it youself, or go to [r/LocalLLaMA](https://www.reddit.com/r/LocalLLaMA/).

**Comment by Rushang007** [comment]
OKey @eastriverlee 
Thanks

**Comment by Rushang007** [comment]
Hello @eastriverlee 

I'm getting a crash on the real device (iPhone XR), but it's working on the simulator.

Please check screenshort
 
![Untitled](https://github.com/eastriverlee/LLM.swift/assets/16713953/d76945a3-4779-4b41-a2c5-6712c5cd8a55)

**Comment by eastriverlee** [comment]
i don't want to be rude @Rushang007, but you need to start thinking and researching on your own before asking anything to anyone.  
there're a lot of information in the screenshot that tell you what is happening exactly, so there is nothing you can't solve by yourself.

it returned nil because there is no model in `self.path`.
you gave absolute address that's only available in mac, that's why it only worked in simulator, because simulator can read the file in your mac.

**Comment by Rushang007** [comment]
@eastriverlee 

i'm new in model (means how to use it). i saw your repo and its related to my assignment So i just started to implement.

FYI :- when i got this crash ,i debug it and checked self.path was NOT returned nil.

I thought we could use it the same way as use any .mp3 or other file  which is also working in simulator (available in mac) as well as device.
